### ISSUE TITLE
Error in Product CRUD: Seller

### ISSUE THREAD

**Issue by vigneshwarvj** [fssa-batch3/dhanush.selvam__web_project#3]
### Description of issue
If I click the category, the page was redirected into 127.00... something.
I couldn't able to choose the category and create the product

```
Path:      /pages/cattle/sell_details1.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kowmart.netlify.app%2Fpages%2Fcattle%2Fsell_details1.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kowmart.netlify.app/pages/cattle/sell_details1.html)

**Comment by DhanushS212003** [comment]
Thank you, Vigneshwar, for finding the issue, I have solved it.

**Comment by vigneshwarvj** [comment]
Thank you for solving the issue, Dhanush. I checked it. It worked.
