### ISSUE TITLE
Not showing the cattle detail

### ISSUE THREAD

**Issue by vigneshwarvj** [fssa-batch3/dhanush.selvam__web_project#4]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYzIxMzE2Y2YtNGNlZi00Y2Y5LTg4ODEtNDgxMGE5ZDJjNzBhIiwiZGVwbG95X2lkIjoiNjQzNjdhOTVlOTEyYTgwMDA4YWNkZWYwIiwiaWQiOiIwMjkxZTk3Yi1jYzI0LTQyYzEtYjNkMC1lYTE2NjZkMmU0YjgifQ==)

### Description of issue
If I click the more gir in cattles page, the page was redirected into like this.

```
Path:      /pages/cattle%20details/cow/c1?breed=Gir&cattle_id=846bb3db-d183-4add-bcc6-0a976d9085c1&user_id=1111111111
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kowmart.netlify.app%2Fpages%2Fcattle%2520details%2Fcow%2Fc1%3Fbreed%3DGir%26cattle_id%3D846bb3db-d183-4add-bcc6-0a976d9085c1%26user_id%3D1111111111&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kowmart.netlify.app/pages/cattle%20details/cow/c1?breed=Gir&cattle_id=846bb3db-d183-4add-bcc6-0a976d9085c1&user_id=1111111111)

**Comment by DhanushS212003** [comment]
Thank you, Vigneshwar, for finding the issue, I have solved it.

**Comment by vigneshwarvj** [comment]
Thank you for solving the issue, Dhanush. I checked it. It worked.
