### ISSUE TITLE
Align the cattles properly

### ISSUE THREAD

**Issue by vigneshwarvj** [fssa-batch3/dhanush.selvam__web_project#5]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYzIxMzE2Y2YtNGNlZi00Y2Y5LTg4ODEtNDgxMGE5ZDJjNzBhIiwiZGVwbG95X2lkIjoiNjQzNjdhOTVlOTEyYTgwMDA4YWNkZWYwIiwiaWQiOiI4NGRkOTA1OC1iMzA2LTQwZmUtYTQ3ZS1mYjdkNTU1OWE0MWQifQ==)

### Description of issue
The cattles are doesn't aligned properly.

```
Path:      /pages/cattle/b-sprofile.html?user-id=2222222222
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kowmart.netlify.app%2Fpages%2Fcattle%2Fb-sprofile.html%3Fuser-id%3D2222222222&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kowmart.netlify.app/pages/cattle/b-sprofile.html?user-id=2222222222)

**Comment by DhanushS212003** [comment]
Thank you, Vigneshwar, for finding the issue; I have solved it.

**Comment by vigneshwarvj** [comment]
Thank you for solving the issue, Dhanush. I checked it. It worked.
