### ISSUE TITLE
Add a cursor pointer in button

### ISSUE THREAD

**Issue by vigneshwarvj** [fssa-batch3/dhanush.selvam__web_project#6]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiYzIxMzE2Y2YtNGNlZi00Y2Y5LTg4ODEtNDgxMGE5ZDJjNzBhIiwiZGVwbG95X2lkIjoiNjQzNjdhOTVlOTEyYTgwMDA4YWNkZWYwIiwiaWQiOiIxYjhmODZjOC0yMjM1LTQ0MDItYjkzOS0xNzVlN2Y3MzNkMWYifQ==)

### Description of issue
Add Cursor pointer, when the user clicking any button. 

```
Path:      /pages/cattle/sell_details1.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kowmart.netlify.app%2Fpages%2Fcattle%2Fsell_details1.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kowmart.netlify.app/pages/cattle/sell_details1.html)

**Comment by DhanushS212003** [comment]
It is not at all an issue. Please ensure that the issues are correct before creating them.

**Comment by vigneshwarvj** [comment]
Okay! Thank you.
