### ISSUE TITLE
Documentation should be clear

### ISSUE THREAD

**Issue by vigneshwarvj** [fssa-batch3/dhanush.selvam__web_project#7]
### Description of issue
Documentation should be clear.

```
Path:      /index.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kowmart.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kowmart.netlify.app/index.html)

**Comment by DhanushS212003** [comment]
I have already written the readme file very clearly. I don't know why you can't understand it.

**Comment by vigneshwarvj** [comment]
Sorry. I can't understand properly. So that, I created this issue.
